### ISSUE TITLE
Valhalla combat but just the block, for dual wield.

### ISSUE THREAD

**Issue by Llamandowski** [Arkay-1248/Do-Not-Go-Gentle#11]
Valhalla combat - https://www.nexusmods.com/skyrimspecialedition/mods/64741

**Why do you think that this mod would fit for DNGG?**
It has a different style to the "bash to parry" that is in the list, you would only block a moment before the strike lands.
Not considering any particular preference between the two, this one works on dual wield.
When it comes to balance,with the current mod, if you miss the parry you lose stamina because of the bash. 
The other mod would drain a miniscule amount of stamina for the block duration (requiem does it i believe) and then, if you missed, you'd get damage converted to stamina if you were too early or just damage if you were late.
You can chain them both forever on enemies but i guess it takes skill...?

**Did you try the mod? How is the gameplay with it?**
I tried it in another list, it was there only for the timed block aswell. it plays largely the same as the current parry mod but it allows to make late timed blocks when recovering from actions where you would not have time to bash. Whether this is desirable or not you decide.

**Did you try to add the mod to the list already?**
I did not, i would never modify a wabbajack list, come on. it's rude.

**Additional context**
Dual wield has always been bad anyway so nobody would care if you didn't change a mod for it i bet.
Nice list, bye.

**Comment by Arkay-1248** [comment]
Done in the next update
