### ISSUE TITLE
Mod suggestion: Jump Behavior Overhaul

### ISSUE THREAD

**Issue by ghost** [Arkay-1248/Do-Not-Go-Gentle#12]
**What's the name of the mod and please provide a nexus link to it**
Jump Behavior Overhaul at https://www.nexusmods.com/skyrimspecialedition/mods/36889

**Why do you think that this mod would fit for DNGG?**
Smooth and dynamic jumping animations that look especially great when you spend a ton of time in 3rd person, as in this list. I'm especially found of the landing animations (hero for warrior, roll for thief, slow fall for mage).

**Did you try the mod? How is the gameplay with it?**
I've played with this mod for many hours in the Tranquility Wabbajack list, where I was introduced to it.

**Did you try to add the mod to the list already?**
I have not tried to add it to DNGG.

**Additional context**
N/A

**Comment by Arkay-1248** [comment]
Yep, I'll probably add this one. Testing it tomorrow. Thanks
