### ISSUE TITLE
Add survival mechanics

### ISSUE THREAD

**Issue by TheStrikerFalcon** [Arkay-1248/Do-Not-Go-Gentle#15]
Sunhelm Survival and Needs
https://www.nexusmods.com/skyrimspecialedition/mods/39414?tab=description
It is very compatible with every other mod on the list. All you have to do is remove the prompt for survival mode with "Survival Mode Prompt Removed" and it won't have any compatibility issues https://www.nexusmods.com/skyrimspecialedition/mods/59049

**Did you try the mod? How is the gameplay with it?**
Very good. Works every time. The best survival mod available in my opinion.

**Did you try to add the mod to the list already?**
Yep. Very easy to patch and compatible with requiem. A patch is provided with "Requiem Patch Central": https://www.nexusmods.com/skyrimspecialedition/mods/64410?tab=files

I didn't like the removal of survival mechanics when playing DNGG. I tried disabling the CC Survival Mode weight modifier with this mod list by installing a mod to do so but it does not work. None of the food fills you up.

Sunhelm is super compatible with Requiem, and there won't be any issues with Survival Mode if Survival Mode is never activated in-game. You don't need to worry about what LOOT says. You could try installing a patch for Requiem and CC Survival Mode of course but in my opinion Sunhelm is just better in every way.

**Comment by Arkay-1248** [comment]
I don't enjoy Survivalist gameplay, so I won't be adding it. Survival Mode Prompt Removed is already in the list, but adding sunhelm would be up to you.
