### ISSUE TITLE
Don't like the gamepad control scheme

### ISSUE THREAD

**Issue by TheStrikerFalcon** [Arkay-1248/Do-Not-Go-Gentle#16]
I can't change weapons quickly with SkyUI like I could before.

If I am wrong, could you provide an instruction manual for these controls?

**Comment by Arkay-1248** [comment]
The combo of these two mods is what Ruvaak uses: 
https://www.nexusmods.com/skyrimspecialedition/mods/27184
https://www.nexusmods.com/skyrimspecialedition/mods/29381

I added them too because Ruvaak's author exclusively plays with gamepad and said this is the best combination. I hope it helps
