### ISSUE TITLE
Legacy of the Dragonborn?

### ISSUE THREAD

**Issue by TheStrikerFalcon** [Arkay-1248/Do-Not-Go-Gentle#17]
Can you either add LotD to this list, or Lawbringer?

I am looking for an ultimate modlist that has requiem and lots of quest mods installed, with perhaps Lawbringer.
That would be my ultimate modlist

Unfortunately, I suck at modding.

If you do this, can you make MoreHUD an optional feature? I personally don't like MoreHUD when used with LotD, as it is immersion-breaking to be omniscient about what items you do or don't have in your museum.

**Comment by Arkay-1248** [comment]
I will never add LotD to any list I ever make. Lawbringer just has some issues, so I don't really wanna deal with that. LotD is and always will be a hard no.
