### ISSUE TITLE
Sneak Animation Not Working While Holding Spell In Left Hand

### ISSUE THREAD

**Issue by arielle-allice** [Arkay-1248/Do-Not-Go-Gentle#18]
Basically title. The sneak animation works properly when you don't have a spell equipped in your hand but as soon as a spell is present, my character stands and the legs are completely static and don't move. Tested this on a new character (video incl) just to make sure this wasn't a save problem due to updating this morning.

https://user-images.githubusercontent.com/69109345/201958199-c2fb0f4b-8205-4b7d-84f6-ee213260eb92.mp4

Modlist version
Latest

Did you add any additional mods?
Nope

YOU MUST DECLARE IF YOU HAVE MODIFIED THE LIST.
Did not change anything.

**Comment by arielle-allice** [comment]
Happens with dual-wielding spells as well when trying to sneak.

**Comment by Arkay-1248** [comment]
This is fixed by removing\changing the dodge mod, as was done in the latest update
