### ISSUE TITLE
Mod Suggestion - Lucien Follower

### ISSUE THREAD

**Issue by believeinyuna** [Arkay-1248/Do-Not-Go-Gentle#2]
**What's the name of the mod and please provide a nexus link to it**
Lucien 
https://www.nexusmods.com/skyrimspecialedition/mods/20035

**Why do you think that this mod would fit for DNGG?**
More follower diversity, expansive quest, a good companion for main quest + DLCs, has interactions with (nearly?) all creation club content, the voice acting + writing are good (imo), can be levelled up as tank/warrior, archer or mage so fits into multiple playstyles. 

**Did you try the mod? How is the gameplay with it?**
I've used Lucien in multiple hundred hour saves with different Modlists and he's always been a delight, however I haven't used him with Requiem before. I think his unique levelling + spell learning makes him interactive and fun to have with you, plus he comments on much of what you do. 

**Did you try to add the mod to the list already?**
No, there is a patch (https://www.nexusmods.com/skyrimspecialedition/mods/64050) for Requiem and Lucien, but it requires running reqtificator and I'm not touching that as I saw you disable some things when running it. Without it I think he would be utterly useless.

**Additional context**
He interacts with multiple other followers, like Inigo, Auri, Kaidan, there are a few more, so if you wanted to add any of those along side him, that's another bonus. He also interacts with Lydia.

**Comment by Arkay-1248** [comment]
Personally, I like Lucien as a mod, but he has constantly aggroed people for some reason in every other list I have played. I think I am kind of happy with the followers I have right now, but this _may_ be an addition later on

**Comment by Arkay-1248** [comment]
I still don't want to add him enough to bother. I'm sorry
