### ISSUE TITLE
Lux Via suggestion

### ISSUE THREAD

**Issue by AlenVex** [Arkay-1248/Do-Not-Go-Gentle#25]
**What's the name of the mod and please provide a nexus link to it**
Lux Via at https://www.nexusmods.com/skyrimspecialedition/mods/63588

**Why do you think that this mod would fit for DNGG?**
This mod really adds a lot of great atmosphere and makes the world traversal more exciting, there are always little details on the road that are unique to each hold. This mod changes bridges and overhauls a couple of excising roadside areas like the forsworn sacked shack on the way to Markarth.

**Did you try the mod? How is the gameplay with it?**
I did add this mod to DNGG and had 0 issues. As far I am aware it is script free and it does not add and NPCs. I found that the mod really helped the atmosphere and made the world more immersive and aesthetic. There was no FPS difference for me with this mod as wel which is really cool. I especially love how it overhauls the are around Windhelm, a typically empty and somewhat boring area. It adds skeletons on the stakes. overhauls the bridge to the left of the city and adds more light sources. It's awesome.

**Did you try to add the mod to the list already?**
Yes, I did. I just installed Lux Lia and the unofficial patch: https://www.nexusmods.com/skyrimspecialedition/mods/62248 as well as the Whiterun repaired bridge version: https://www.nexusmods.com/skyrimspecialedition/mods/72384
I had 0 issues with adding the mod and while playing the list.

**Additional context**
It's just a very compatible and easy to install mod that adds A LOT to the game, at least in my experience it was seamless. I freaking adore this list but my biggest issue with it is kind of the "emptiness" of some areas.

**Comment by AlenVex** [comment]
This is the only Lux Via video showcase I found on YT but there are a lot of pictures on the Nexus mod page. https://www.youtube.com/watch?v=uhM6SzGBh2I

I pretty much just slapped the mod in the list, didn't  do anything else and it worked great like that, no issues or CTDs with it.

**Comment by Arkay-1248** [comment]
Added
