### ISSUE TITLE
Stave Church of Skyrim

### ISSUE THREAD

**Issue by AlenVex** [Arkay-1248/Do-Not-Go-Gentle#26]
**What's the name of the mod and please provide a nexus link to it**
My awesome mod suggestion at https://www.nexusmods.com/skyrimspecialedition/mods/44480

**Why do you think that this mod would fit for DNGG?**
It adds several Nordic stave churches to the world, they look just... amazing. It was always exciting to explore the world and stumble upon one and it makes the game so much more atmospheric and immersive!

**Did you try the mod? How is the gameplay with it?**
The models for the churches are exquisite and very well done, they fit with the CV enb so freaking well. It's just a beautiful addition to any skyrim modlist imo.

**Did you try to add the mod to the list already?**
Yes, I did, and it gave me no issues since there are no additional NPCs added or any scripts. As said before, it's amazing to discover these churches and it adds excitement to the exploration.

**Additional context**
[https://postimg.cc/D4z4n6Xp](url)
A screenshot with the CV enb.

**Comment by Arkay-1248** [comment]
Yes

**Comment by Arkay-1248** [comment]
Added
