### ISSUE TITLE
Elysium Estate, best Home for DNGG.

### ISSUE THREAD

**Issue by AlenVex** [Arkay-1248/Do-Not-Go-Gentle#27]
**What's the name of the mod and please provide a nexus link to it**
[https://www.nexusmods.com/skyrimspecialedition/mods/4119](url)
This is a new Home buuuut it can practically be like LOTD but not bloated. I'm sorry in advance for the large wall of text, I just really adore DNGG and want it to be number 1 list on the planet! 

**Why do you think that this mod would fit for DNGG?**
The location is perfect when you don't have fast travel! It adds more to the Whiterun area without a huge FPS drop since it's still in the distance. It looks amazing and lore friendly, just like Tundra Estate from CC but in a much better location for fast travel. It is located just outside of Whiterun stables, close to the Guard Tower that gets attacked but the dragon in the main quest.

**Did you try the mod? How is the gameplay with it?**
I did and omg it is so good! I love the basement, it has tons of displays for trophies of all kinds, like the armor, daedric artifacts, claws, masks, quirky quest items like Pelagius's hip bone or interesting skulls found throughout the game, it can satisfy that completionism itch! The trophy basement is small and cozy, not like the museum from LOTD. And honestly, it never looks empty, even if you don't complete the collection. 

OMG and the book shelves! I loved collecting all the books and displaying them in the bedroom, I think it really addss to the enjoyment of the game for me and many others I imagine. It became my permanent base and I kept all my companions there, it's just amazing. Please, Arkay, look into it, it would benefit this amazing list you've created, I swear.

**Did you try to add the mod to the list already?**
Yep. It most likely needs a LUX and LUX Orbis patch, which I believe can be automatically installed in the LUX FOMOD if LUX is reinstalled, because the lighting inside, with CV enb, looked too bright for me and I didn't want to reinstall LUX in case I mess something up. But other than the lighting(which can be changed with Lux) the home was perfect! No clipping or anything. If it was included offically and DynDOLOD includes it it would be amazing.

I also installed the Buyable Key patch for it https://www.nexusmods.com/skyrimspecialedition/mods/38169 it will be sold in the Honningbrew Meadery for around 9000 gold depending on your speech skill. I believe we need more ways to dump our endless amounts of money in Skyrim! 

**Additional context**
Here's a video showcasing the home! https://www.youtube.com/watch?v=ft-G0N8A-Tg
It's honestly one of the best homes I've seen and it always gives my motivation to explore and play the game so I could fill the trophy basement, that is its contribution to the game's enjoyment. Pretty please look into this mod, it's awesome!

**Comment by Arkay-1248** [comment]
Done
