### ISSUE TITLE
Routa - Stormcloak and Warrior cabin

### ISSUE THREAD

**Issue by AlenVex** [Arkay-1248/Do-Not-Go-Gentle#28]
**What's the name of the mod and please provide a nexus link to it**
A new player home located outside of Windhelm. 
https://www.nexusmods.com/skyrimspecialedition/mods/1193

**Why do you think that this mod would fit for DNGG?**
The only thing this amazing list needs imo is some more esthetic changes to the world that would make it feel a bit more lived in and expansive. So I was specifically looking into houses that are just outside the cities and close to the stables for the carriage traveling. This home makes the area just outside Windhelm less empty which is always a plus.

**Did you try the mod? How is the gameplay with it?**
Tried it, played with it on my nord character and it was great. I actually used the non-Stormcloak version which is included in the mod's files. I think the non-Stormcloak is better because it doesn't lock players into the role, you can live in the non-Stormcload version even as an Imperial sympathizer and be golden! So it would fit better for the modlist that is played by many different players.

**Did you try to add the mod to the list already?**
Yes, and I had no issues. The only patch I had to install is the Lux Via patch since... I also added Lux Via to the list, don't kill me xD
Lux Via is freaking amazing tho, please consider it too, I added it in the suggestions as well UwU

**Additional context**
And here is a video showcase! https://www.youtube.com/watch?v=hF8dLtqdRyE

**Comment by Arkay-1248** [comment]
Probably

**Comment by Arkay-1248** [comment]
Done
