### ISSUE TITLE
DNGG - True Armor and Dodge Mod suggestion

### ISSUE THREAD

**Issue by TrueGitHubRoman** [Arkay-1248/Do-Not-Go-Gentle#3]
**What's the name of the mod and please provide a nexus link to it**
True Armor - https://www.nexusmods.com/skyrimspecialedition/mods/15921

Dodge Mod - Can't decide between TK Dodge or TUDM
https://www.nexusmods.com/skyrimspecialedition/mods/15309
https://www.nexusmods.com/skyrimspecialedition/mods/63000

**Why do you think that this mod would fit for DNGG?**
True armor makes combat more dynamic. It forces players to choose the right weapon against lightly or heavily armored opponents. It doesn't just make melee combat more difficult and engaging, though, it does the same for ranged and magic by providing certain armors resistances against certain types of magic. All in all just great for making heavily armored characters feel like tanks and lightly armored characters feel nimble.

A dodge mod feels essential for requiem.

**Did you try the mod? How is the gameplay with it?**
Yes, I've played with True Armor and dodges. True Armor allows characters to face harder enemies at lower levels but also forces them to manage their stamina and such better.

Same with dodge mods.

**Did you try to add the mod to the list already?**
Haven't played DNGG yet, but will download it soon.

**Additional context**
Stay cool

**Comment by Arkay-1248** [comment]
Requiem already does both of these things to my liking. It has a dodge mechanic in the Light Armor(Evasion) tree, and it completely overhauls the armor ratings and mechanics.
