### ISSUE TITLE
EasierRider's Dungeon Pack?

### ISSUE THREAD

**Issue by AlenVex** [Arkay-1248/Do-Not-Go-Gentle#30]
**What's the name of the mod and please provide a nexus link to it**

EasierRider's Dungeon Pack: https://www.nexusmods.com/skyrimspecialedition/mods/2218

Requiem patch on Nexus: https://www.nexusmods.com/skyrimspecialedition/mods/76940?_gl=1%2Ayrlev0%2A_ga%2AMTQ5Mjc0MTIzMC4xNjQ1MzI4Njcz%2A_ga_N0TELNQ37M%2AMTY4MjQwODA2My42OC4xLjE2ODI0MDgzMjguMC4wLjA.&tab=files

**Why do you think that this mod would fit for DNGG?**
Just due to playing this list so much, it can become pretty repetitive, so adding additional dungeons can really help replayability and spice up the game. The list is already great, but sometimes seeing the same dungeons on each new playthrough can get boring, or maybe I just play DNGG to much, who knows! But this mod in particular is not bloated, it only adds 8 dungeons, not 300, so that allows each dungeon to be detailed and unique, the pictures look amazing.

**Did you try the mod? How is the gameplay with it?**
Played with EasierRider's Dungeon Pack back in the day but don't have a lot of experience with it; it is used in a lot of modlists so it must be pretty stable, right?

**Did you try to add the mod to the list already?**
No... I don't know how to Requify properly so that's why I'm here lol. 

**Additional context**
Add any other context or screenshots about the feature request here. Idk.

**Comment by Arkay-1248** [comment]
Another nice one
