### ISSUE TITLE
Unique Uniques?

### ISSUE THREAD

**Issue by AlenVex** [Arkay-1248/Do-Not-Go-Gentle#31]
**What's the name of the mod and please provide a nexus link to it**
Unique Uniques: https://www.nexusmods.com/skyrimspecialedition/mods/3334?tab=videos

Requiem Patch: https://www.nexusmods.com/skyrimspecialedition/mods/44190?_gl=1*9enz6f*_ga*MTQ5Mjc0MTIzMC4xNjQ1MzI4Njcz*_ga_N0TELNQ37M*MTY4MjQwODA2My42OC4xLjE2ODI0MDk3MzQuMC4wLjA.

**Why do you think that this mod would fit for DNGG?**
I don't know if this really fits into DNGG's philosophy, but it's just always nice to see that a unique weapon has a unique appearance as well. The weapons are not over-the-top anime style, they fit in the world quite well and the textures look really good, much better than vanilla. It's not a super necessary addition, but it's just nice to have some uniqueness to the weapons.

**Did you try the mod? How is the gameplay with it?**
No, I just watched some videos showcasing the look of the weapons. There are probably better replacers, but none that I've seen.

**Did you try to add the mod to the list already?**
Nope, I can't Requify properly, nor play any other list than DNGG for more than an hour so... yeah, I'll suggest it I guess.

**Additional context**
Video showcase of the weapons: https://www.youtube.com/watch?v=0D8795wVxE8

**Comment by Arkay-1248** [comment]
Nice
