### ISSUE TITLE
True Storms for more weather diversity without modifying the lighting. It will just add rain, fog and storms.

### ISSUE THREAD

**Issue by AlenVex** [Arkay-1248/Do-Not-Go-Gentle#33]
**What's the name of the mod and please provide a nexus link to it**
True Storms: https://www.nexusmods.com/skyrimspecialedition/mods/2472?tab=files

**Why do you think that this mod would fit for DNGG?**
So, I've been enjoying DNGG, but I realized that with the weather mod gone, we now lack the weather diversity shown in this video for example: https://youtube.com/clip/UgkxwMln5NcGnsX9lqgjnuQcUVqccyg1XoBR
I will never forget the awe and atmosphere that these moments brought and they were in large the reason I fell in love with the list. 

Now that the graphics took a very different direction, we need to think of more ways how we can bring these moments back without the use of weather mods, since they seem to be out of the question for now. 
Lately, playing the list, everything just felt bland, especially when you visit the same old Skyrim for the 100th time. Weather diversity will help spice up the world and make each day unique.

**Did you try the mod? How is the gameplay with it?**
I did play the mod and included a small comparison of vanilla DNGG weather and True Storms on the bottom. I really do miss the visuals of the older versions (like on your YouTube video) sometimes, but I understand that it's your vision. I do however think that more weather diversity is always good, and if visibility is an issue... I think that great atmospheric and cinematic moments are worth lowered visibility. Maybe one day you will find a great weather mod you'll love, I feel like they can help make the game more immersive and atmospheric, but they are a pain to deal with for sure.

**Did you try to add the mod to the list already?**
Yes, and there were no issues, prior to that I was looking for a weather mod for DNGG that would not alter the lighting at all so it would work with CV ENB. True storms only adds the weather effects so it seemed perfect. It is compatible with the Storm Lightning for SSE and pretty much everything else.

**Additional context**
Here is a small comparison of vanilla DNGG weather and True Storms on the same saves. (hopefully the link works oof)
https://imgur.com/a/ylNsQPM

**Comment by AlenVex** [comment]
And there's also this mod that alters the default particles for vanilla snow and rain, it has good screenshots for comparison:
https://www.nexusmods.com/skyrimspecialedition/mods/15171

**Comment by AlenVex** [comment]
And this mod as well changes the rain and snow: https://www.nexusmods.com/skyrimspecialedition/mods/8006?tab=description

But True Storms, subjectively, was the best in how it made the storms more intense, although the rain droplets aren't ideal. It was  the only mod out these 3 that added low visibility to blizzards.

**Comment by Arkay-1248** [comment]
Might not be needed in the next update
