### ISSUE TITLE
Bigger Moons for added wow-effect at night.

### ISSUE THREAD

**Issue by AlenVex** [Arkay-1248/Do-Not-Go-Gentle#34]
**What's the name of the mod and please provide a nexus link to it**
Bigger Moons: https://www.nexusmods.com/skyrimspecialedition/mods/29792?tab=files

**Why do you think that this mod would fit for DNGG?**
Honestly. It just looks cool. That's it :]

**Did you try the mod? How is the gameplay with it?**
Yep, I attached some screenshots on the bottom.

**Did you try to add the mod to the list already?**
Yep, and there are no issues, loaded after the weather and moon mods.

**Additional context**
Screenshots with the bigger moons: https://imgur.com/a/qorG1Km

**Comment by Arkay-1248** [comment]
Added
