### ISSUE TITLE
Dungeons - Revisited. Expands the vanilla dungeons with new pathways (great design actually, as it turns out)

### ISSUE THREAD

**Issue by AlenVex** [Arkay-1248/Do-Not-Go-Gentle#35]
**What's the name of the mod and please provide a nexus link to it**
Dungeons - Revisited https://www.nexusmods.com/skyrimspecialedition/mods/51798
(No need for a Requiem patch since the NPCs added don't need manual patching)

**Why do you think that this mod would fit for DNGG?**
It makes the old & boring vanilla dungeons bigger and more interesting to visit again. It mostly adds additional paths, so if the player wants to speedrun, they still can, foregoing the new path. 
The list:
Bleak Falls Barrow
Ustengrav
Embershard Mine
Steepfall Burrow
Halted Stream Camp
White River Watch
Hillgrund's Tomb
Broken Fang Cave

**Did you try the mod? How is the gameplay with it?**
Finally tried it, and, I was skeptical at first, but it lowkey blew my mind how well done the mod is. It actually opens some pathways that allow stealth kills, it was awesome. It makes dungeons longer but not too long, where it'd be tedious and boring. You can bypass the new path completely if you want. I think it fits Requiem and DNGG perfectly.

**Did you try to add the mod to the list already?** 
I'm actually doing it right now and looking at it in SSEEdit (I'm not running the Requificator though, cuz I don't trust myself.) Will see if it breaks the list lol.

**Additional context**
I was also considering suggesting Inconvenient Dungeons https://www.nexusmods.com/skyrimspecialedition/mods/66784. 
But, no. It was in Arisen modlist, and I loved it, made the dungeons feel almost survival-like. But, it's very controversial, most people hated it, and I can understand why. 
But hey, it exists if you'd wanna check it out, and it makes dungeons feel new and expands the vanilla short game-loop. People will hate it though lol.

**Comment by Arkay-1248** [comment]
Added
