### ISSUE TITLE
VIGILANT NPCs face overhaul

### ISSUE THREAD

**Issue by AlenVex** [Arkay-1248/Do-Not-Go-Gentle#36]
**What's the name of the mod and please provide a nexus link to it**
https://www.nexusmods.com/skyrimspecialedition/mods/22146?tab=description

**Why do you think that this mod would fit for DNGG?**
I mean, c'mon. Potato faces begone!

**Did you try the mod? How is the gameplay with it?**
I did, but my SSEedit doesn't work anymore for some reason, so I can't check if this mod alters NPCs' stats. It shouldn't, but I can't check for that, sorry!

**Did you try to add the mod to the list already?**

**Additional context**

**Comment by Arkay-1248** [comment]
Done. It doesn't even have an .esp
