### ISSUE TITLE
Unable to download  HQ College of Winterhold

### ISSUE THREAD

**Issue by BarryValley** [Arkay-1248/Do-Not-Go-Gentle#37]
**Upload your crashlog**

If you've crashed, upload your crashlog from `C:\Users\Username(unique to your PC)\Documents\My Games\Skyrim Special Edition\SKSE`. Reports of crashes that do not include a crashlog will be **ignored and closed.**

**Required: Modlist.txt**

Unable to find this txt file

**Describe the bug**
When trying to download DNGG it get to nearly the end of the download and stop when trying to download HQ College of Winterhold, I have tried to find this mod but I am unable to source it.

**To Reproduce**

1. Go to Wabbajack and install DNGG
2. Error comes up when trying to intstal HQ College of WinterHold

**Expected behavior**
N/A

**Screenshots**
N/A

**Modlist version**
2.7.1

**Did you add any additional mods?**

***YOU MUST DECLARE IF YOU HAVE MODIFIED THE LIST.***
[Wabbajack.current.log](https://github.com/Arkay-1248/Do-Not-Go-Gentle/files/13170888/Wabbajack.current.log)

**Comment by Arkay-1248** [comment]
This is handled via the discord server
