### ISSUE TITLE
Mod Suggestion - Encumbrance Message Gone

### ISSUE THREAD

**Issue by believeinyuna** [Arkay-1248/Do-Not-Go-Gentle#4]
**What's the name of the mod and please provide a nexus link to it**
Encumbrance Message Gone https://www.nexusmods.com/skyrimspecialedition/mods/20770

**Why do you think that this mod would fit for DNGG?**
because of the sleep mod used to increase carry weight, you often have more carry weight than your actual base carry weight, so the game thinks you're over encumbered when you aren't. this means you're likely to get spammed with the over encumbered message in the top left every few minutes, which happened to me. 

**Did you try the mod? How is the gameplay with it?**
i did try it. it considerably reduced my frustration when playing, because my eyes were always drawn to the new notification, but it was nearly always that exact same over encumbered one, when i was running around fine and not actually over encumbered. 

**Did you try to add the mod to the list already?**
yes, i did. it works, i placed it above dyndolod.esp without any problems.

**Additional context**
maybe if you don't want to force this on people, you could make it an optional plugin?

**Comment by Arkay-1248** [comment]
It is now available in the optional separator. Thanks
