### ISSUE TITLE
-HIMBO-

### ISSUE THREAD

**Issue by philfycasual** [Arkay-1248/Do-Not-Go-Gentle#5]
**What's the name of the mod and please provide a nexus link to it**
Highly Improved Male Body Overhaul -HIMBO- at https://www.nexusmods.com/skyrimspecialedition/mods/46311?tab=files

**Why do you think that this mod would fit for DNGG?**
For parity with CBBE?

**Did you try the mod? How is the gameplay with it?**
It just offers the same level of customisability for male bodies as we have with female ones. As far as actual gameplay goes, it doesn't provide much outside of immersion.

**Did you try to add the mod to the list already?**
Yes -- as far as I can tell it's pretty seamless an add-on. Obviously 'requires' the HIMBO refits for any added outfits or armours, but this should be trivial, I believe

**Additional context**

**Comment by Arkay-1248** [comment]
I have actually cut down cbbe to just a body replacer, and the male body got the same treatment with the skin mod, if I remember correctly. I don't think I will be adding HIMBO. Sorry
