### ISSUE TITLE
Suggestion: Contextual Crosshair

### ISSUE THREAD

**Issue by ghost** [Arkay-1248/Do-Not-Go-Gentle#9]
**What's the name of the mod and please provide a nexus link to it**
Contextual Crosshair https://www.nexusmods.com/skyrimspecialedition/mods/63980

**Why do you think that this mod would fit for DNGG?**
Minimalistic dot crosshair and less intrusive allowing for more focus while playing DNGG.

**Did you try the mod? How is the gameplay with it?**
Yes, it's great. The crosshair isn't up your face and only shows when needed.

**Did you try to add the mod to the list already?**
Nope. But tried it on Wildlander and its wonderful

**Additional context**
It adds a small dot as crosshair instead of the big vanilla crosshair.
There is a video showcase in the modpage, skip to 3:40 for the Contextual Crosshair overview

**Comment by Arkay-1248** [comment]
This mod is already in the list. Feel free to tailor the .ini file to your liking though
